#include "../clientlib/decompiler_imports.dl"

.decl StorageRead(func: Function, slot: Value)
.output StorageRead

StorageRead(func, slot) :-
  SLOAD(stmt, index, _),
  Variable_Value(index, slot),
  Statement_Block(stmt, block),
  InFunction(block, func).

.decl StorageWrite(func: Function, slot: Value)
.output StorageWrite

StorageWrite(func, slot) :-
  SSTORE(stmt, index, _),
  Variable_Value(index, slot),
  Statement_Block(stmt, block),
  InFunction(block, func).

.decl MemoryOp(stmt: Statement)

MemoryOp(stmt) :- MLOAD(stmt, _, _).
MemoryOp(stmt) :- MSTORE(stmt, _, _).

.decl MemoryIndex(stmt: Statement, index: Variable)

MemoryIndex(stmt, index) :- MLOAD(stmt, index, _).
MemoryIndex(stmt, index) :- MSTORE(stmt, index, _).

.decl MemoryAddrResolved(stmt: Statement, addr: symbol)

MemoryAddrResolved(stmt, "0x40 [free-mem-ptr]") :-
  MemoryIndex(stmt, index),
  Variable_Value(index, "0x40").

MemoryAddrResolved(stmt, val) :-
  MemoryIndex(stmt, index),
  Variable_Value(index, val),
  val != "0x40".

MemoryAddrResolved(stmt, cat("*(", cat(p, cat(")+", k)))) :-
  MemoryIndex(stmt, index),
  (ADD(_, base, off, index) ; ADD(_, off, base, index)),
  MLOAD(_, pvar, base),
  Variable_Value(pvar, p),
  Variable_Value(off, k).

.decl MemoryAddr(stmt: Statement, addr: symbol)

MemoryAddr(stmt, addr) :- MemoryAddrResolved(stmt, addr).

MemoryAddr(stmt, "computed") :-
  MemoryOp(stmt),
  !MemoryAddrResolved(stmt, _).

.decl MemoryRead(func: Function, stmt: Statement, addr: symbol)
.output MemoryRead

MemoryRead(func, stmt, addr) :-
  MLOAD(stmt, _, _),
  MemoryAddr(stmt, addr),
  Statement_Block(stmt, block),
  InFunction(block, func).

.decl MemoryWrite(func: Function, stmt: Statement, addr: symbol)
.output MemoryWrite

MemoryWrite(func, stmt, addr) :-
  MSTORE(stmt, _, _),
  MemoryAddr(stmt, addr),
  Statement_Block(stmt, block),
  InFunction(block, func).
