#include "../clientlib/decompiler_imports.dl"
#include "../clientlib/memory_modeling/memory_modeling.dl"
#include "../clientlib/storage_modeling/storage_modeling.dl"

.decl ConstCondJump(block: Block, alwaysTaken: number)
ConstCondJump(block, 1) :- JUMPI(s, _, cond), Statement_Block(s, block), Variable_Value(cond, v), v != "0x0".
ConstCondJump(block, 0) :- JUMPI(s, _, cond), Statement_Block(s, block), Variable_Value(cond, "0x0").

.decl InfeasibleEdge(from: Block, to: Block)
InfeasibleEdge(f, t) :- ConstCondJump(f, 1), FallthroughEdge(f, t).
InfeasibleEdge(f, t) :- ConstCondJump(f, 0), LocalBlockEdge(f, t), !FallthroughEdge(f, t).

.decl FeasibleEdge(from: Block, to: Block)
FeasibleEdge(f, t) :- LocalBlockEdge(f, t), !InfeasibleEdge(f, t).

.decl ReachableBlock(block: Block)
ReachableBlock(b) :- FunctionEntry(b).
ReachableBlock(t) :- ReachableBlock(f), FeasibleEdge(f, t).

.decl StorageRead(func: Function, cons: StorageConstruct)
.output StorageRead

StorageRead(func, cons) :-
  StorageLoad(stmt, cons, _),
  Statement_Block(stmt, block), ReachableBlock(block), InFunction(block, func).

StorageRead(func, cons) :-
  StorageStmtKindAndConstruct(stmt, $ArrayLength(), $Storage(), cons),
  SLOAD(stmt, _, _),
  Statement_Block(stmt, block), ReachableBlock(block), InFunction(block, func).

.decl StorageWrite(func: Function, cons: StorageConstruct)
.output StorageWrite

StorageWrite(func, cons) :-
  StorageStore(stmt, cons, _),
  Statement_Block(stmt, block), ReachableBlock(block), InFunction(block, func).

StorageWrite(func, cons) :-
  StorageStmtKindAndConstruct(stmt, $ArrayLength(), $Storage(), cons),
  SSTORE(stmt, _, _),
  Statement_Block(stmt, block), ReachableBlock(block), InFunction(block, func).
